# Generated by Django 4.1.3 on 2022-11-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(height_field=100, upload_to='images', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(height_field=100, upload_to='images', width_field=100)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeBookAPI.category')),
            ],
        ),
    ]
